import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: "#FFFCF4",
  },
  container: {
    flex: 1,
    padding: 32,
    paddingTop: 12,
    gap: 16,
    paddingBottom: 100,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 12,
  },
  titleInput: {
    fontSize: 25,
    margin: 0,
    fontWeight: "700",
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
  },
  roundedInput: {
    borderRadius: 8,
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 2,
    paddingLeft: 10,
    paddingRight: 10,
  },
  descriptionInput: {
    fontSize: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
  },
  weekdayContainer: {
    flexDirection: "row",
    marginBottom: 16,
    display: "flex",
    borderRadius: 12,
    backgroundColor: "#ccc",
    columnGap: 1,
    overflow: "hidden",
  },
  weekdayButton: {
    padding: 11,
    backgroundColor: "#ccc",
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  weekdayButtonSelected: {
    backgroundColor: "#ffffff",
  },
  weekdayText: {
    fontSize: 12,
  },
  weekdayTextSelected: {
    color: "black",
    alignSelf: "center",
  },
  inputContainer: { marginLeft: -8, height: 55 },
  emojiInputContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "100%",
    flexWrap: "nowrap",
    overflow: "hidden",
    marginBottom: -15,
    paddingHorizontal: 8,
  },
  label: {
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 12,
  },
  createButton: {
    width: 165,
    alignSelf: "center",
    borderRadius: 20,
    backgroundColor: "#000000",
    padding: 16,
    marginTop: 20,
  },
  createButtonDisabled: {
    backgroundColor: "#cccccc",
  },
  createButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
  },
  listItem: {
    padding: 16,
    paddingTop: 21,
    paddingBottom: 21,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
    marginBottom: 8,
    borderRadius: 20,
    width: 100,
    rowGap: 8,
    boxShadow: "1px 4px 15px 2px rgba(0,0,0,0.66)",
  },
  backgroundSelected: {
    backgroundColor: "#F4FFE5",
  },
  listItemShadow: {
    shadowColor: "#212121",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 11,
  },
  flatListContainer: {
    maxHeight: "80%",
    display: "flex",
    columnGap: 100,
    padding: 20,
  },
  listItemTitle: {
    fontSize: 15,
    fontWeight: "700",
  },
  listItemPoints: {
    fontSize: 25,
    fontWeight: "700",
  },
  listItemText: {
    fontSize: 15,
    fontWeight: "500",
  },
  checkboxContainer: {
    position: "absolute",
    top: 8,
    right: 8,
  },
  checkmarkIcon: {
    height: 24,
    marginTop: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  dateText: {
    marginLeft: 8,
    fontSize: 16,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalButton: {
    alignSelf: "flex-end",
    padding: 16,
  },
  modalButtonText: {
    color: "#007AFF",
    fontSize: 16,
    fontWeight: "600",
  },
  toggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  assigneeContainer: {
    gap: 8,
  },
  assigneeButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  assigneeButtonSelected: {
    backgroundColor: "#F4FFE5",
    borderColor: "#4CAF50",
  },
  assigneeAvatar: {
    fontSize: 20,
    marginRight: 8,
  },
  assigneeName: {
    marginLeft: 8,
    fontSize: 16,
    flex: 1,
  },
  rotationOrder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#4CAF50",
    justifyContent: "center",
    alignItems: "center",
  },
  rotationOrderText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
});
